# _config.yml

title: Cyril's GitHub Page
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal site hosted on GitHub Pages.
  Iâ€™ll share projects, notes, and experiments here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikliryc.github.io" # replace with your GitHub Pages URL

# Build settings
theme: jekyll-theme-midnight # you can change to another supported Jekyll theme

# Optional settings
markdown: kramdown
