title: Cyril's GitHub Page
description: >-
  Welcome to my personal site hosted on GitHub Pages.
  Iâ€™ll share projects, notes, and experiments here.
baseurl: ""
url: "https://mikliryc.github.io"

theme: jekyll-theme-slate
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

sass:
  style: compressed

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - buildLocal.bat
  - README.md
  - my_commits.txt
  - legacy_index.md
  - .git
  - .idea
  - .jekyll-cache
  - _site