title: Cyril's GitHub Page
description: >-
  _config.yml 파일에 있음
baseurl: ""
url: "https://mikliryc.github.io"

markdown: kramdown

permalink: /blog/:year/:month/:day/:title/

sass:
  style: compressed

plugins: []

exclude:
  - Gemfile
  - Gemfile.lock
  - buildLocal.bat
  - README.md
  - my_commits.txt
  - legacy_index.md
  - .git
  - .idea
  - .jekyll-cache
  - _site
